### ISSUE TITLE
[error] qgraph destroys base summary function for characters

### ISSUE THREAD

**Issue by huelf** [SachaEpskamp/qgraph#9]
Hi,
after loading package qgraph the base summary function does no longer work properly. It outputs all characters of class character instead of only 5.

Example:
```
iris2 <- iris
iris2$char <- as.character(iris$Petal.Width)
summary(iris2)
library(qgraph)
summary(iris2)
```
R Version 3.4.1
qgraph Version 1.4.3

Regards
Hans

**Comment by mrkwht** [comment]
I'm having the same issue.  The problem appears to be due to the network package, which seems to be invoked when using qgraph, regardless if qgraph is loaded or the namespace is invoked.  

In code below, the summary function works correctly. Then after defining a function based on function in qgraph namespace, the summary function breaks.  Debug shows that this is due to the fact that summary.character is now being invoked (note that calling the debug function makes R start  using the network::summary.character too).  It's not clear whether qgraph can fix this problem without addressing the issues in the network package.

```
summary(data.frame(letters[1:5],stringsAsFactors=F))
cor_auto <- qgraph::cor_auto
summary(data.frame(letters[1:5],stringsAsFactors=F))
debugonce(network::summary.character)
summary(data.frame(letters[1:5],stringsAsFactors=F))
```

R Version: 3.5.0
qgraph version 1.5

**Comment by SachaEpskamp** [comment]
Thanks for reporting. I removed the sna dependency that caused this!
